version: '3.8'

services:
  backend:
    image: spravinkumar9952/streamer:v4.2
    container_name: backend-app
    ports:
      - "9999:9999"
      - "9998:9998"
    env_file:
      - ./backend/.env
    restart: unless-stopped
    working_dir: /app
    command: ["npm", "run", "start:all"]

  frontend:
    image: spravinkumar9952/streamer-frontend:v6.3
    container_name: frontend-app
    expose:
      - "80"  # Optional: expose separately if needed
    env_file:
      - ./frontend/.env
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
