apiVersion: apps/v1
kind: Deployment
metadata:
    namespace: streamer
    name: streamer-backend
    labels:
        app: streamer
        component: backend
spec:
    replicas: 2
    selector:
        matchLabels:
            app: streamer
            component: backend
    template:
        metadata:
            labels:
                app: streamer
                component: backend
        spec:
            containers:
                - name: backend
                  image: spravinkumar9952/streamer:v2
                  ports:
                      - containerPort: 9999
                        name: http
                      - containerPort: 9998
                        name: socket
                  env:
                      - name: NODE_ENV
                        value: "development"
                      - name: MONGO_CONNECTION_STR
                        value: "mongodb+srv://spravinkumar9952:XUenHQVQstQjky7u@maincluster.vamac.mongodb.net/?retryWrites=true&w=majority&appName=mainCluster"
                      - name: UI_BASE_URL
                        value: "http://localhost:3000"
                      - name: HTTP_PORT
                        value: "9999"
                      - name: SOCKET_PORT
                        value: "9998"
                      - name: REDIS_URL
                        value: "redis://streamer-redis:6379"
                      - name: JWT_SECRET
                        valueFrom:
                            secretKeyRef:
                                name: streamer-secrets
                                key: JWT_SECRET
                      - name: GOOGLE_CLIENT_ID
                        valueFrom:
                            secretKeyRef:
                                name: streamer-secrets
                                key: GOOGLE_CLIENT_ID
                      - name: GOOGLE_CLIENT_SECRET
                        valueFrom:
                            secretKeyRef:
                                name: streamer-secrets
                                key: GOOGLE_CLIENT_SECRET
                      - name: SOCKET_SERVER_URL
                        value: "http://streamer-backend:9998"
                      - name: HTTP_SERVER_URL
                        value: "http://streamer-backend:9999"
                      - name: SESSION_SECRET
                        value: "ppreaavrilniknugmoalrd2197003822000033"
                      - name: UI_REDIRECT_URL
                        value: "http://localhost:3000/home"
                      - name: SECRET_KEY
                        value: "ppreaavrilniknugmoalrd2197003822000033"

                  resources:
                      requests:
                          memory: "256Mi"
                          cpu: "250m"
                      limits:
                          memory: "512Mi"
                          cpu: "500m"
                  livenessProbe:
                      httpGet:
                          path: /health
                          port: http
                      initialDelaySeconds: 30
                      periodSeconds: 10
                  readinessProbe:
                      httpGet:
                          path: /health
                          port: http
                      initialDelaySeconds: 5
                      periodSeconds: 5
